export const loveAndHumorArray = [
    "My girlfriend told me to stop impersonating a flamingo. I had to put my foot down.",
    "Why did the scarecrow win an award? Because he was outstanding in his field... of love!",
    "Love is like a fine wine; it gets better with time, and sometimes it gives you a headache.",
    "I love you more than coffee, and that's saying a latte.",
    "Why don't scientists trust atoms in love? Because they can't make up their minds!",
    "I asked my dog about true love. He just wagged his tail. Guess he's a romantic.",
    "Why did the computer go to couples therapy? It had too many relationship issues.",
    "My love life is like a spreadsheet - full of calculations and always needing more functions.",
    "Why did the romance novel go to therapy? It had too many plot issues.",
    "Love is like Wi-Fi. It’s invisible but connects you to what you need.",
    "Why did the heart go to school? To get a little heart-smart!",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "Relationships are a lot like algebra. You look at your X and wonder Y.",
    "I love you with all my pizza. That's a whole lot of love!",
    "Why did the two bananas go to couples therapy? They couldn't find the appeal anymore.",
    "My wife told me I should embrace my mistakes. So I gave her a hug.",
    "Love is like a rollercoaster; it has its ups and downs, and sometimes it makes you scream.",
    "Why did the Valentine's Day card get arrested? It was filled with love and affection!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "My girlfriend told me to stop impersonating a flamingo. I had to put my foot down.",
    "Why did the scarecrow win an award? Because he was outstanding in his field... of love!",
    "Love is like a fine wine; it gets better with time, and sometimes it gives you a headache.",
    "I love you more than coffee, and that's saying a latte.",
    "Why don't scientists trust atoms in love? Because they can't make up their minds!",
    "I asked my dog about true love. He just wagged his tail. Guess he's a romantic.",
    "Why did the computer go to couples therapy? It had too many relationship issues.",
    "My love life is like a spreadsheet - full of calculations and always needing more functions.",
    "Why did the romance novel go to therapy? It had too many plot issues.",
    "Love is like Wi-Fi. It’s invisible but connects you to what you need.",
    "Why did the heart go to school? To get a little heart-smart!",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "Relationships are a lot like algebra. You look at your X and wonder Y.",
    "I love you with all my pizza. That's a whole lot of love!",
    "Why did the two bananas go to couples therapy? They couldn't find the appeal anymore.",
    "My wife told me I should embrace my mistakes. So I gave her a hug.",
    "Love is like a rollercoaster; it has its ups and downs, and sometimes it makes you scream.",
    "Why did the Valentine's Day card get arrested? It was filled with love and affection!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "My girlfriend told me to stop impersonating a flamingo. I had to put my foot down.",
    "Why did the scarecrow win an award? Because he was outstanding in his field... of love!",
    "Love is like a fine wine; it gets better with time, and sometimes it gives you a headache.",
    "I love you more than coffee, and that's saying a latte.",
    "Why don't scientists trust atoms in love? Because they can't make up their minds!",
    "I asked my dog about true love. He just wagged his tail. Guess he's a romantic.",
    "Why did the computer go to couples therapy? It had too many relationship issues.",
    "My love life is like a spreadsheet - full of calculations and always needing more functions.",
    "Why did the romance novel go to therapy? It had too many plot issues.",
    "Love is like Wi-Fi. It’s invisible but connects you to what you need.",
    "Why did the heart go to school? To get a little heart-smart!",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "Relationships are a lot like algebra. You look at your X and wonder Y.",
    "I love you with all my pizza. That's a whole lot of love!",
    "Why did the two bananas go to couples therapy? They couldn't find the appeal anymore.",
    "My wife told me I should embrace my mistakes. So I gave her a hug.",
    "Love is like a rollercoaster; it has its ups and downs, and sometimes it makes you scream.",
    "Why did the Valentine's Day card get arrested? It was filled with love and affection!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "My girlfriend told me to stop impersonating a flamingo. I had to put my foot down.",
    "Why did the scarecrow win an award? Because he was outstanding in his field... of love!",
    "Love is like a fine wine; it gets better with time, and sometimes it gives you a headache.",
    "I love you more than coffee, and that's saying a latte.",
    "Why don't scientists trust atoms in love? Because they can't make up their minds!",
    "I asked my dog about true love. He just wagged his tail. Guess he's a romantic.",
    "Why did the computer go to couples therapy? It had too many relationship issues.",
    "My love life is like a spreadsheet - full of calculations and always needing more functions.",
    "Why did the romance novel go to therapy? It had too many plot issues.",
    "Love is like Wi-Fi. It’s invisible but connects you to what you need.",
    "Why did the heart go to school? To get a little heart-smart!",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "Relationships are a lot like algebra. You look at your X and wonder Y.",
    "I love you with all my pizza. That's a whole lot of love!",
    "Why did the two bananas go to couples therapy? They couldn't find the appeal anymore.",
    "My wife told me I should embrace my mistakes. So I gave her a hug.",
    "Love is like a rollercoaster; it has its ups and downs, and sometimes it makes you scream.",
    "Why did the Valentine's Day card get arrested? It was filled with love and affection!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "My girlfriend told me to stop impersonating a flamingo. I had to put my foot down.",
    "Why did the scarecrow win an award? Because he was outstanding in his field... of love!",
    "Love is like a fine wine; it gets better with time, and sometimes it gives you a headache.",
    "I love you more than coffee, and that's saying a latte.",
    "Why don't scientists trust atoms in love? Because they can't make up their minds!",
    "I asked my dog about true love. He just wagged his tail. Guess he's a romantic.",
    "Why did the computer go to couples therapy? It had too many relationship issues.",
    "My love life is like a spreadsheet - full of calculations and always needing more functions.",
    "Why did the romance novel go to therapy? It had too many plot issues.",
    "Love is like Wi-Fi. It’s invisible but connects you to what you need.",
    "Why did the heart go to school? To get a little heart-smart!",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "Relationships are a lot like algebra. You look at your X and wonder Y.",
    "I love you with all my pizza. That's a whole lot of love!",
    "Why did the two bananas go to couples therapy? They couldn't find the appeal anymore.",
    "My wife told me I should embrace my mistakes. So I gave her a hug.",
    "Love is like a rollercoaster; it has its ups and downs, and sometimes it makes you scream.",
    "Why did the Valentine's Day card get arrested? It was filled with love and affection!",
  ];
  
  